import { z } from "zod";

/**
 * Task schema — defines the shape of a task record.
 *
 * This schema is shared across all CRUD endpoints and is used for:
 * - OpenAPI spec generation (request/response schemas)
 * - Input validation (body + path params)
 * - D1 column inference (keys of the schema = valid SQL columns)
 *
 * Important: `id` is optional because it's auto-generated by D1.
 * Use Zod v4 syntax throughout (e.g., z.iso.datetime(), not z.string().datetime()).
 */
export const TaskSchema = z.object({
  id: z.number().optional().describe("Auto-generated task ID"),
  title: z.string().min(1).max(200).describe("Task title"),
  description: z.string().max(1000).optional().describe("Task description"),
  completed: z.boolean().optional().default(false).describe("Whether the task is completed"),
  created_at: z.string().optional().describe("Creation timestamp (ISO 8601)"),
});

/**
 * Shared model metadata used by all D1 endpoints.
 * - tableName: must match the D1 migration table name
 * - primaryKeys: path params are derived from these (e.g., /tasks/:id)
 */
export const taskMeta = {
  model: {
    tableName: "tasks",
    schema: TaskSchema,
    primaryKeys: ["id"],
  },
};
