version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cloudflare:
        patterns:
          - "@cloudflare/*"
          - wrangler
      dev:
        patterns:
          - "@types/*"
          - "vitest*"
          - typescript
          - hono
          - itty-router
    ignore:
      - dependency-name: '\*'
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
