site_name: itty-router-openapi
site_description: OpenAPI 3 schema generator and validator for Cloudflare Workers
site_url: https://cloudflare.github.io/itty-router-openapi/
docs_dir: pages
theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  language: en
repo_name: cloudflare/itty-router-openapi
repo_url: https://github.com/cloudflare/itty-router-openapi
edit_uri: ''
plugins:
  - search
  - termynal
  - markdownextradata:
      data: data
nav:
  - itty-router-openapi: index.md
  - types.md
  - User Guide:
      - user-guide/first-steps.md
      - user-guide/path-parameters.md
      - user-guide/query-parameters.md
      - user-guide/request-body.md
      - user-guide/response-format.md
      - user-guide/router-options.md
      - user-guide/nested-routers.md
      - user-guide/security.md
      - user-guide/cors.md
      - user-guide/middleware.md
      - user-guide/migrating-from-itty-router.md
  - Advanced User Guide:
      - advanced-user-guide/reusable-schemas.md
      - advanced-user-guide/custom-response-formats.md
      - advanced-user-guide/custom-response-headers.md
      - advanced-user-guide/openai-plugin.md
      - advanced-user-guide/ci-cd-pipelines.md
      - advanced-user-guide/event-listener-worker.md
      - advanced-user-guide/hiding-routes-in-openapi-schema.md
      - advanced-user-guide/openapi-schema-customizations.md
      - advanced-user-guide/streaming-responses.md
  - migrating-to-1.0.md
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: pages
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudflare/itty-router-openapi
