name: Create Pull Request Prerelease

on: pull_request

jobs:
  build:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Build & Publish a Prerelease to the Adhoc Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - run: npm install --frozen-lockfile
      - run: npm run build

      - name: Create package
        run: npm pack

      - name: Upload packaged chanfana artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-chanfana-${{ github.event.number }} # encode the PR number into the artifact name
          path: chanfana-*.tgz

      - name: 'Comment on PR with Link'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.number }}
          message: |
            🧪 A prerelease is available for testing 🧪

            You can install this latest build in your project with:

            ```sh
            npm install --save https://prerelease-registry.devprod.cloudflare.dev/chanfana/runs/${{ github.run_id }}/npm-package-chanfana-${{ github.event.number }}
            ```

            Or you can immediately run this with `npx`:

            ```sh
            npx https://prerelease-registry.devprod.cloudflare.dev/chanfana/runs/${{ github.run_id }}/npm-package-chanfana-${{ github.event.number }}
            ```
